config/routes.rb
Rails.application.routes.draw do
  get 'matches/add_scorers'
  get 'matches/team_matches'
  post 'matches/invitation', to: 'matches#create_invitation'
  delete 'matches/invitation', to: 'matches#destroy_invitation'
  post 'matches/set_dependencies', to: 'matches#set_dependencies'
  resources :matches

  get 'invitations', to: 'invitations#index'

  post 'invitations', to: 'invitations#create'
  delete 'invitations', to: 'invitations#destroy'

  resources :teams do
    member do
      delete 'delete_from_team'
    end
  end

  resources :leagues do
    member do
      get 'scorers'
      get 'matches'
    end
  end

  resources :towns

  devise_for :users, :path_prefix => 'admin'

  resources :users

  get 'home/index'
  get 'home/search'
  get 'home/rules'
  get 'home/about'
  get 'home/contact'

  root 'home#index'

end

app/models/league.rb
class League < ActiveRecord::Base
  belongs_to  :town
  has_many :teams, dependent: :destroy
  has_many :matches, dependent: :destroy

  def description
    if division == 0
      return "Ekstraklasa"
    elsif division == 1
      return "1. Liga"
    else
      "Liga #{division}.#{group}"
    end
  end

  def description_with_town
    if division == 0
      return "#{town.name}: Ekstraklasa"
    elsif division == 1
      return "#{town.name}: 1. Liga"
    else
      "#{town.name}: Liga #{division}.#{group}"
    end
  end
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  before_action :set_league, only: [:show, :edit, :update, :destroy, :scorers, :matches]
  before_action :authenticate_user!
  before_filter :valid_is_admin, except: [:show, :scorers, :matches]

  respond_to :html

  def index
    @leagues = League.all.paginate(:page => params[:page], :per_page => 20)
    respond_with(@leagues)
  end

  def show
    @sorted_teams = @league.teams.sort_by{|team| [team.points, team.scored - team.lost, team.scored]}.reverse
    respond_with(@league)
  end

  def scorers
    scorers = []
    for team in @league.teams
      scorers += team.players.select{|player| player.goals > 0}
    end
    @sorted_scorers = scorers.sort_by{|scorer| scorer.goals}.reverse
  end

  def matches
    @matches = @league.matches.select{|match| match.confirmed}.sort_by{|match| match.date}.reverse
  end

  def new
    @league = League.new
    @towns  = Town.all
    respond_with(@league)
  end

  def edit
    @towns = Town.all
    @lowest_div = @league.town.leagues.sort_by{:division}[-1][:division]
    @lowest_group = @league.town.leagues.select{|league| league.division == @lowest_div}.count
  end

  def create
    @league = League.new(league_params)

    @towns = Town.all
    town = @league.town
    lowest_div = town.leagues.sort_by{:division}[-1]
    if lowest_div == nil
      @league.division = 0
      @league.group = 1
    else
      lowest_div = lowest_div[:division]
      if lowest_div == 0
        @league.division = 1
        @league.group = 1
      elsif lowest_div == 1
        @league.division = 2
        @league.group = 1
      else
        groups_in_lowest_div = town.leagues.select{|league| league.division == lowest_div}.count
        if groups_in_lowest_div == 2**(lowest_div - 1)
          @league.division = lowest_div + 1
          @league.group = 1
        else
          @league.division = lowest_div
          @league.group = groups_in_lowest_div + 1
        end
      end
    end

    @league.save
    respond_with(@league)
  end

  def update
    @towns = Town.all
    @league.update(league_params)
    respond_with(@league)
  end

  def destroy
    @league.destroy
    respond_with(@league)
  end

  private
    def set_league
      @league = League.find(params[:id])
    end

    def league_params
      params.require(:league).permit(:division, :group, :town_id)
    end

    def valid_is_admin
      if current_user.is_admin == false
        redirect_to root_path, alert: 'Nie posiadasz uprawnień administratora.'
      end
    end
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/views/leagues/edit.html.haml
.page-header
  %h1= 'Edytuj ligę'

= form_for @league do |f|
  - if @league.errors.any?
    #error_explanation
      %h2= "#{pluralize(@league.errors.count, "error")} prohibited this league from being saved:"
      %ul
        - @league.errors.full_messages.each do |msg|
          %li= msg


  .form-group
    = f.label 'Miasto'
    .controls
      = f.collection_select :town_id, @towns, :id, :name, {}, {class: 'selectpicker'}
  .form-group
    = f.label 'Poziom'
    .controls
      = f.number_field :division, min: 0, max: @lowest_div + 1, class: 'form-control', style: 'width: 60px;'
  .form-group
    = f.label 'Grupa'
    .controls
      = f.number_field :group, min: 1, max: @lowest_group + 1, class: 'form-control', style: 'width: 60px;'

  .actions
    = f.submit 'Utwórz', :class => 'btn btn-primary', :style => 'color: white;'
    = link_to 'Powrót do lig', leagues_path, :class => 'btn btn-default'

app/views/leagues/index.html.haml
= render 'shared/admin_panel'

%table.table.table-striped
  %thead
    %tr
      %th= 'Miasto'
      %th= 'Poziom'
      %th= 'Drużyn'
      %th

  - @leagues.each do |league|
    %tr
      %td= league.town.name
      %td= league.description
      %td= league.teams.count
      %td
        = link_to 'Pokaż', league, :class => 'btn btn-default btn-xs'
        = link_to 'Edytuj', edit_league_path(league), :class => 'btn btn-default btn-xs'
        = link_to 'Usuń', league, :method => :delete, :data => { :confirm => 'Jesteś pewny?' },
                                                    :class => 'btn btn-danger btn-xs', :style => 'color: white;'

%center
  = will_paginate @leagues, renderer: BootstrapPagination::Rails
= link_to 'Nowa liga', new_league_path, :class => 'btn btn-primary', :style => 'color: white;'

app/views/leagues/matches.html.haml
.page-header
  %h1
    .label.label-default= link_to @league.town.name, town_path(@league.town), :style => 'color: white;'
    = @league.description

%ul.nav.nav-tabs
  %li= link_to 'Tabela', league_path(@league)
  %li= link_to 'Strzelcy', scorers_league_path(@league)
  %li.active= link_to 'Mecze', matches_league_path(@league)

%br
%center
  - for match in @matches
    - if current_user.team == match.home or current_user.team == match.visitor
      %a{href: match_path(match), style: 'font-weight: bold;'}
        = match.date
        &nbsp &nbsp &nbsp
        = match.vs
        &nbsp &nbsp
        = match.result
        %br
    - else
      %a{href: match_path(match)}
        = match.date
        &nbsp &nbsp &nbsp
        = match.vs
        &nbsp &nbsp
        = match.result
        %br

%br
- if current_user.team != nil and current_user.team.captain == current_user
  = link_to 'Dodaj raport meczowy', new_match_path, :class => 'btn btn-primary', :style => 'color: white;'

app/views/leagues/new.html.haml
.page-header
  %h1= 'Nowa liga'

= form_for @league do |f|
  - if @league.errors.any?
    #error_explanation
      %h2= "#{pluralize(@league.errors.count, "error")} prohibited this league from being saved:"
      %ul
        - @league.errors.full_messages.each do |msg|
          %li= msg


  .form-group
    = f.label 'Miasto'
    .controls
      = f.collection_select :town_id, @towns, :id, :name, {}, {class: 'selectpicker'}

  .actions
    = f.submit 'Utwórz', :class => 'btn btn-primary', :style => 'color: white;'
    = link_to 'Powrót do lig', leagues_path, :class => 'btn btn-default'

app/views/leagues/scorers.html.haml
.page-header
  %h1
    .label.label-default= link_to @league.town.name, town_path(@league.town), :style => 'color: white;'
    = @league.description

%ul.nav.nav-tabs
  %li= link_to 'Tabela', league_path(@league)
  %li.active= link_to 'Strzelcy', scorers_league_path(@league)
  %li= link_to 'Mecze', matches_league_path(@league)

%br

%center
  %div.panel.panel-default{:style => 'width: 50%;'}
    %table.table
      %thead
        %tr
          %th= '#'
          %th= 'Zawodnik'
          %th= 'Klub'
          %th
            %center= 'Gole'

      %tbody
        - @sorted_scorers.each_with_index do |scorer, i|
          %tr
            %td= i + 1
            %td
              = link_to scorer.full_name, user_path(scorer)
              - if i == 0
                %span.glyphicon.glyphicon-star{:style => 'color: gold;'}
            %td= scorer.team.name
            %td
              %b
                %center= scorer.goals

app/views/leagues/show.html.haml
.page-header
  %h1
    .label.label-default= link_to @league.town.name, town_path(@league.town), :style => 'color: white;'
    = @league.description

%ul.nav.nav-tabs
  %li.active= link_to 'Tabela', league_path(@league)
  %li= link_to 'Strzelcy', scorers_league_path(@league)
  %li= link_to 'Mecze', matches_league_path(@league)

%br

%center
  %div.panel.panel-default{:style => 'width: 80%;'}
    %table.table
      %thead
        %tr
          %th= '#'
          %th= 'Drużyna'
          %th
            %center= 'Mecze'
          %th
            %center= 'Gole +'
          %th
            %center= 'Gole -'
          %th
            %center= '+/-'
          %th
            %center= 'Punkty'

      %tbody
        - @sorted_teams.each_with_index do |team, i|
          - style = ''
          - if i < 2
            - style = 'background-color: #dff0d8;'
          - elsif i > 7
            - if @league.division > 0
              - style = 'background-color: #f2dede;'
            - elsif i > 9
              - style = 'background-color: #f2dede;'
          - if user_signed_in? and current_user.team == team
            - style += 'font-weight: bold;'
          %tr{:style => style}
            %td= i + 1
            %td= link_to team.name, team_path(team)
            %td
              %center= team.home_matches.select{|match| match.confirmed}.count + team.visitor_matches.select{|match| match.confirmed}.count
            %td
              %center= team.scored
            %td
              %center= team.lost
            %td
              %center= team.scored - team.lost
            %td
              %b
                %center= team.points

%span.badge{:style => 'background-color: #dff0d8; color: #3c763d'}= '1-2'
= 'Awans do wyższej klasy rozgrywkowej'
%br
- if @league.division == 0
  %span.badge{:style => 'background-color: #f2dede; color: #a94442'}= '11-12'
- else
  %span.badge{:style => 'background-color: #f2dede; color: #a94442'}= '9-12'
= 'Spadek do niższej klasy rozgrywkowej'
%br
  %br

- if current_user.is_admin
  = link_to 'Edytuj', edit_league_path(@league), :class => 'btn btn-default'