config/routes.rb
Rails.application.routes.draw do
  get 'matches/add_scorers'
  get 'matches/team_matches'
  post 'matches/invitation', to: 'matches#create_invitation'
  delete 'matches/invitation', to: 'matches#destroy_invitation'
  post 'matches/set_dependencies', to: 'matches#set_dependencies'
  resources :matches

  get 'invitations', to: 'invitations#index'

  post 'invitations', to: 'invitations#create'
  delete 'invitations', to: 'invitations#destroy'

  resources :teams do
    member do
      delete 'delete_from_team'
    end
  end

  resources :leagues do
    member do
      get 'scorers'
      get 'matches'
    end
  end

  resources :towns

  devise_for :users, :path_prefix => 'admin'

  resources :users

  get 'home/index'
  get 'home/search'
  get 'home/rules'
  get 'home/about'
  get 'home/contact'

  root 'home#index'

end

app/views/shared/_admin_panel.html.haml
%ul.nav.nav-tabs
  - if current_page?(users_path)
    %li.active= link_to 'Użytkownicy', users_path
  - else
    %li= link_to 'Użytkownicy', users_path
  - if current_page?(towns_path)
    %li.active= link_to 'Miasta', towns_path
  - else
    %li= link_to 'Miasta', towns_path
  - if current_page?(leagues_path)
    %li.active= link_to 'Ligi', leagues_path
  - else
    %li= link_to 'Ligi', leagues_path
  - if current_page?(teams_path)
    %li.active= link_to 'Zespoły', teams_path
  - else
    %li= link_to 'Zespoły', teams_path
  - if current_page?(matches_path)
    %li.active= link_to 'Mecze', matches_path
  - else
    %li= link_to 'Mecze', matches_path

%br

app/views/shared/_side_panel.html.haml
- if user_signed_in? and current_user.team != nil and current_user.team.league != nil
  %div.panel.panel-default
    %table.table
      %thead
        %tr
          %td{colspan: 4, style: 'line-height: 10px;'}
            %center
              %b= link_to current_user.team.league.description_with_town, league_path(current_user.team.league)

      %tbody
        - current_user.team.league.teams.sort_by{|team| [team.points, team.scored - team.lost, team.scored]}.reverse.each_with_index do |team, i|
          - style = ''
          - if i < 2
            - style = 'background-color: #dff0d8;'
          - elsif i > 7
            - if current_user.team.league.division > 0
              - style = 'background-color: #f2dede;'
            - elsif i > 9
              - style = 'background-color: #f2dede;'
          - if user_signed_in? and current_user.team == team
            - style += 'font-weight: bold;'
          %tr{:style => style}
            %td{style: 'line-height: 12px;'}= i + 1
            %td{style: 'line-height: 12px;'}= link_to team.name, team_path(team)
            %td{style: 'line-height: 12px;'}
              %center= team.home_matches.select{|match| match.confirmed}.count + team.visitor_matches.select{|match| match.confirmed}.count
            %td{style: 'width: 22px; text-align: right; line-height: 12px;'}
              %b= team.points
  - invs = current_user.team.send_match_invitations.where(:accepted => true)
  - invs += current_user.team.received_match_invitations.where(:accepted => true)
  - if invs.count > 0
    - upcoming_match = invs.sort_by{:date}[-1]
    .panel.panel-info
      .panel-heading
        %b Najbliższy mecz
      .panel-body
        %center
          %h4{:style => 'margin-top: 2px;'}= link_to upcoming_match.sender.name, team_path(upcoming_match.sender)
          %h5= 'vs.'
          %h4{:style => 'margin-top: 5px;'}= link_to upcoming_match.receiver.name, team_path(upcoming_match.receiver)
          .italic{:style => 'font-style: italic;'}= upcoming_match.date.to_s + ', ' + upcoming_match.place.to_s


.panel.panel-info
  .panel-heading
    %b Nawigacja
  %ul.list-group
    %a.list-group-item{href: root_path} Strona główna
    %a.list-group-item{href: home_search_path} Wyszukiwarka
    %a.list-group-item{href: home_rules_path} Zasady
    %a.list-group-item{href: home_about_path} O Kopaczach
    %a.list-group-item{href: home_contact_path} Kontakt