config/routes.rb
Rails.application.routes.draw do
  get 'matches/add_scorers'
  get 'matches/team_matches'
  post 'matches/invitation', to: 'matches#create_invitation'
  delete 'matches/invitation', to: 'matches#destroy_invitation'
  post 'matches/set_dependencies', to: 'matches#set_dependencies'
  resources :matches

  get 'invitations', to: 'invitations#index'

  post 'invitations', to: 'invitations#create'
  delete 'invitations', to: 'invitations#destroy'

  resources :teams do
    member do
      delete 'delete_from_team'
    end
  end

  resources :leagues do
    member do
      get 'scorers'
      get 'matches'
    end
  end

  resources :towns

  devise_for :users, :path_prefix => 'admin'

  resources :users

  get 'home/index'
  get 'home/search'
  get 'home/rules'
  get 'home/about'
  get 'home/contact'

  root 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, only: [:search]
  require 'will_paginate/array'

  def index
    @last_users = User.last(3)
    @last_teams = Team.last(3)
    @last_matches = Match.where(:confirmed => true).last(3)
    if user_signed_in? and current_user.team == nil
      @team = Team.new
    end
    render :layout => 'application'
  end

  def search
    @results = User.none
    if params[:search]
      category_hash = {'1' => [Team], '2' => [User], '3'  => [Town], '4' => [Team, User, Town]}
      category_hash[params[:category]].each do |table|
        if table == User
          if params[:position] == '1'
            @results += table.where('name LIKE ? OR surname LIKE ?', "%#{params[:search]}%", "%#{params[:search]}%")
          else
            @results += table.where('(name LIKE ? OR surname LIKE ?) AND position = ?', "%#{params[:search]}%",
                                                                      "%#{params[:search]}%", params[:position].to_i - 2)
          end
          if params[:free]
            @results.select!{|res| res.team == nil}
          end
        else
          @results += table.where('name LIKE ?', "%#{params[:search]}%")
        end
      end
    end
    @results = @results.paginate(:page => params[:page], :per_page => 12)
    @results_left   = @results.select{|result| @results.index(result) % 3 == 0}
    @results_center = @results.select{|result| @results.index(result) % 3 == 1}
    @results_right  = @results.select{|result| @results.index(result) % 3 == 2}

    @categories = [{id: 1, name: 'Drużyna'}, {id: 2, name: 'Gracz'}, {id: 3, name: 'Miasto'}, {id: 4, name: 'Wszystko'}]
    @positions = [{id: 1, name: 'Dowolna pozycja'}, {id: 2, name: 'Bramkarz'}, {id: 3, name: 'Obrońca'},
                  {id: 4, name: 'Pomocnik'}, {id: 5, name: 'Napastnik'}]
  end

  def rules
  end

  def about
  end

  def contact
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_sidepanel.html.haml
.panel.panel-info
  .panel-heading
    %b Nagłówek
  %ul.list-group
    %a.list-group-item{href: root_path} Link
    %a.list-group-item{href: root_path} Link

app/views/home/about.html.haml
.row
  .col-md-3
    <br /><br />
    = render 'shared/side_panel'
  .col-md-9
    .page-header
      %h1 O Kopaczach
    %p.lead{style: 'font-size: 19px; text-indent: 25px;'}
      = 'Serwis Kopacze umożliwia fanom piłki nożnej zakładanie własnych, amatorskich drużyn oraz rywalizowanie '
      = 'z innymi zespołami w strukturach ligowych.'
    %p.lead{style: 'font-size: 15px; text-indent: 25px;'}
      = 'Jeśli nudzi Cię już zwykłe kopanie piłki z kolegami na podwórku i szukasz większej dawki emocji związanych '
      = 'z kolejnymi rozgrywanymi meczami, jednocześnie dalej traktując piłkę jako zabawę, to ten portal został '
      = 'stworzony z myślą o ludziach dokładnie takich jak Ty. Skrzyknij znajomych lub znajdź sobie nowych partnerów, '
      = 'umawiaj się na mecze i wepnij się na szczyt tabeli w swoim mieście.'

    - if user_signed_in? == false
      %br
        %center
          = link_to 'Załóż konto', new_user_registration_path, class: 'btn btn-primary btn-lg', style: 'color: white;'
          &nbsp
          = link_to 'Zaloguj się', new_user_session_path, class: 'btn btn-info btn-lg', style: 'color: white;'

app/views/home/contact.html.haml
.row
  .col-md-3
    <br /><br />
    = render 'shared/side_panel'
  .col-md-9
    .page-header
      %h1 Kontakt
    %p.lead{style: 'font-size: 19px; text-indent: 25px;'}
      = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vitae vulputate dolor. Morbi turpis orci, '
      = 'varius sit amet enim in, dapibus vestibulum neque. Nullam nec erat eros. Aenean at viverra felis, et laoreet '
      = 'turpis. Aenean eget ante et lectus rutrum consequat. Duis non ipsum eu augue varius pellentesque. Aliquam ut '
      = 'nisl eu lorem consequat ullamcorper. Fusce vel est semper, consequat elit vitae, euismod sapien. Vivamus '
      = 'ultricies sollicitudin lacus id elementum.'
    %p.lead{style: 'font-size: 15px; text-indent: 25px;'}
      In orci tortor, blandit at nunc vel, commodo tempus lacus. Nullam volutpat dui vel velit porta pharetra. Nunc in egestas nisl. Maecenas congue metus a eros accumsan pulvinar. In arcu sapien, tempus ut odio at, luctus dictum arcu. Quisque laoreet vulputate vulputate. Mauris iaculis nec nunc consequat dapibus. Donec vitae nibh nec ligula tincidunt euismod non et risus. Donec congue, nisi eget porta euismod, enim lectus ultricies mauris, eget ornare lacus mauris vitae dui. Pellentesque consectetur odio nec turpis feugiat molestie. Aenean molestie augue ipsum, nec mollis dui maximus in. Nulla placerat dolor velit, quis facilisis quam auctor et.

app/views/home/index.html.haml
- if user_signed_in? and current_user.team == nil
  %div.jumbotron
    .row
      .col-md-8
        %h1= 'Załóż swój zespół!'
        %p=  'Podaj nazwę drużyny i zacznij zabawę w serwisie Kopacze.'
      .col-md-4
        %br
        = form_for @team do |f|
          .form-group-lg
            .controls
              = f.text_field :name, class: 'form-control', style: 'width: 293px;',
                                    required: true, placeholder: 'Nazwa drużyny'
              = f.hidden_field :captain_id, :value => current_user.id
          %br
          .actions
            = f.submit 'Utwórz', :class => 'btn btn-success btn-lg', :style => 'color: white;'
            = link_to 'Dołącz do innej', home_search_path, :class => 'btn btn-info btn-lg', :style => 'color: white;'

- if user_signed_in? and current_user.team != nil and current_user.team.league == nil
  %p.alert.alert-info
    %span.glyphicon.glyphicon-exclamation-sign
    = 'Twoja drużyna nie przynależy jeszcze do żadnej ligi.'
    = 'Poczekaj aż zbierze się odpowiednia liczba drużyn do założenia nowej ligi.'

.row
  .col-md-3
    <br /><br />
    = render 'shared/side_panel'
  .col-md-9
    .page-header
      %h1 Strona główna

    %div.bs-callout.bs-callout-info
      %h4 Ostatnio dołączyli
      .row
        - for i in (0..@last_users.count - 1).reverse_each
          - user = @last_users[i]
          .col-md-4
            %div.jumbotron{style: 'padding: 8px 8px; margin: 10px 0px 0px 0px;'}
              %div.container
                %h4{style: 'color: inherit'}= user.full_name
                %p{style: 'font-size: 115%; color: grey;'}= @position_name[user.position] + ', ' + user.town.name
                %div{style: 'float: right'}
                  - if user_signed_in? and current_user.team != nil and current_user.team.captain == current_user
                    - if current_user.town == user.town and user.team == nil
                      = link_to 'Zaproś', {:controller => 'invitations', :action => 'create',
                                              :user_id => user.id, :team_id => current_user.team.id},
                                              :method => :post, :class => 'btn btn-success btn-xs', :style => 'color: white;'
                  = link_to 'Pokaż', user_path(user), :class => 'btn btn-primary btn-xs',  :style => 'color: white;'
                  - if user_signed_in? and current_user.is_admin
                    = link_to 'Edytuj', edit_user_path(user), :class => 'btn btn-default btn-xs'

    %div.bs-callout.bs-callout-info
      %h4 Ostatnio założone zespoły
      .row
        - for i in (0..@last_teams.count - 1).reverse_each
          - team = @last_teams[i]
          .col-md-4
            %div.jumbotron{style: 'padding: 8px 8px; margin: 10px 0px 0px 0px;'}
              %div.container
                %h4{style: 'color: inherit'}= team.name
                %p{style: 'font-size: 115%; color: grey;'}= 'Drużyna, ' + team.town.name
                %div{style: 'float: right'}
                  - if user_signed_in? and current_user.team == nil and current_user.town == team.town
                    = link_to 'Aplikuj', {:controller => 'invitations', :action => 'create', :user_id => current_user.id,
                                          :team_id => team.id},:method => :post, :class => 'btn btn-success btn-xs',
                                          :style => 'color: white;'
                  = link_to 'Pokaż', team_path(team), :class => 'btn btn-primary btn-xs',  :style => 'color: white;'
                  - if user_signed_in? and current_user.is_admin
                    = link_to 'Edytuj', edit_team_path(team), :class => 'btn btn-default btn-xs'

    %div.bs-callout.bs-callout-info
      %h4 Ostatnio rozegrane mecze
      .row
        - for i in (0..@last_matches.count - 1).reverse_each
          - match = @last_matches[i]
          .col-md-4
            %div.jumbotron{style: 'padding: 8px 8px; margin: 10px 0px 0px 0px;'}
              %div.container
                .row
                  .col-md-10
                    %h4{style: 'color: inherit'}= match.home.name
                  .col-md-2
                    %h4{style: 'color: inherit; float: right;'}= match.home_score
                .row
                  .col-md-10
                    %h4{style: 'color: inherit'}= match.visitor.name
                  .col-md-2
                    %h4{style: 'color: inherit; float: right;'}= match.visitor_score
                %div{style: 'float: right'}
                  = link_to 'Pokaż', match_path(match), :class => 'btn btn-primary btn-xs',  :style => 'color: white;'
                  - if user_signed_in? and current_user.is_admin
                    = link_to 'Edytuj', edit_match_path(match), :class => 'btn btn-default btn-xs'

app/views/home/rules.html.haml
.row
  .col-md-3
    <br /><br />
    = render 'shared/side_panel'
  .col-md-9
    .page-header
      %h1 Zasady
    %p.lead{style: 'font-size: 19px; text-indent: 25px;'}
      = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vitae vulputate dolor. Morbi turpis orci, '
      = 'varius sit amet enim in, dapibus vestibulum neque. Nullam nec erat eros. Aenean at viverra felis, et laoreet '
      = 'turpis. Aenean eget ante et lectus rutrum consequat. Duis non ipsum eu augue varius pellentesque. Aliquam ut '
      = 'nisl eu lorem consequat ullamcorper. Fusce vel est semper, consequat elit vitae, euismod sapien. Vivamus '
      = 'ultricies sollicitudin lacus id elementum.'
    %p.lead{style: 'font-size: 15px; text-indent: 25px;'}
      In orci tortor, blandit at nunc vel, commodo tempus lacus. Nullam volutpat dui vel velit porta pharetra. Nunc in egestas nisl. Maecenas congue metus a eros accumsan pulvinar. In arcu sapien, tempus ut odio at, luctus dictum arcu. Quisque laoreet vulputate vulputate. Mauris iaculis nec nunc consequat dapibus. Donec vitae nibh nec ligula tincidunt euismod non et risus. Donec congue, nisi eget porta euismod, enim lectus ultricies mauris, eget ornare lacus mauris vitae dui. Pellentesque consectetur odio nec turpis feugiat molestie. Aenean molestie augue ipsum, nec mollis dui maximus in. Nulla placerat dolor velit, quis facilisis quam auctor et.
    %p.lead{style: 'font-size: 15px; text-indent: 25px;'}
      Proin risus velit, vestibulum non semper et, finibus in nibh. Sed non lacus sed ligula tempor consequat. Aenean eget vestibulum turpis, at accumsan diam. Mauris vestibulum elit nec erat facilisis, at malesuada velit volutpat. Mauris non orci sapien. Nulla sed ornare felis. Donec ac arcu at nibh iaculis faucibus. Suspendisse tellus leo, malesuada ac dui ut, vulputate iaculis nibh. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec aliquet, nibh vitae varius auctor, arcu dui dapibus risus, nec auctor odio est nec nisi. Cras et dolor eget enim ultrices mattis. Duis consequat dolor at tellus dapibus porta. Curabitur pharetra purus vitae leo porttitor, id tempus arcu imperdiet. Suspendisse efficitur nunc ut ex pretium, at elementum lacus tempus. Nulla et metus ipsum. Aliquam vehicula odio vel tellus vulputate, et finibus nunc faucibus.
    %p.lead{style: 'font-size: 15px; text-indent: 25px;'}
      Aenean eget ligula magna. Integer lobortis magna et cursus venenatis. Pellentesque tincidunt dictum ante a venenatis. Vestibulum mattis, ligula et malesuada condimentum, ligula enim pellentesque neque, ut malesuada tellus erat finibus lorem. Duis quis ipsum tellus. Maecenas hendrerit, neque elementum molestie lacinia, metus dui vehicula sem, nec dapibus magna arcu et turpis. Aenean velit quam, rutrum ac diam at, lacinia commodo elit.
    %p.lead{style: 'font-size: 15px; text-indent: 25px;'}
      Cras ornare dui diam, eu accumsan tellus vulputate quis. Maecenas accumsan lacus at mi aliquam, sed pulvinar tellus dictum. Nam sit amet nisi tristique, consectetur diam ut, vehicula felis. Nunc hendrerit sit amet orci eu blandit. Donec vitae erat nunc. Morbi consectetur nibh urna, et faucibus magna dictum et. Vestibulum quis justo eu nisl facilisis ultricies ac at tellus. Maecenas a augue mauris. Donec ac nibh in leo volutpat ornare. Morbi ullamcorper, purus nec interdum aliquet, tellus mi pharetra sem, ac facilisis lacus enim eu sapien.

app/views/home/search.html.haml
.row
  .col-md-3
    <br /><br />
    = render 'shared/side_panel'
  .col-md-9
    .page-header
      %h1 Wyszukiwarka

    = form_tag home_search_path, :method => :get do
      %table
        %tbody
          %tr
            %td.has-feedback
              %i.glyphicon.glyphicon-search.form-control-feedback
              =text_field_tag :search, params[:search], class: 'form-control', placeholder: 'Szukaj...'
            %td{style: 'width: 15px;'}
            %td= select_tag :category, options_for_select(@categories.collect{|cat| [cat[:name], cat[:id]]}, params[:category]),
                                                                                                class: 'selectpicker cat'
            %td.player{style: 'width: 15px; display: none;'}
            %td.player{style: 'display: none;'}
              = select_tag :position, options_for_select(@positions.collect{|pos| [pos[:name], pos[:id]]}, params[:position]),
                                                                                                class: 'selectpicker'
            %td.player{style: 'width: 15px; display: none;'}
            %td.player{style: 'display: none;'}
              %div
                %b= 'Wolny'
              %div{style: 'margin-top: -2px;'}
                %center= check_box_tag :free, 1, params[:free]
            %td{style: 'width: 15px;'}
            %td= submit_tag 'Szukaj', :name => nil, :class => 'btn btn-primary', :style => 'color: white;'
    .row
      - for results in [@results_left, @results_center, @results_right]
        .col-md-4
          - for result in results
            %div.jumbotron{style: 'padding: 8px 8px;'}
              %div.container
                - if result.is_a? User
                  %h4= result.full_name
                - else
                  %h4= result.name
                %p{style: 'font-size: 115%; color: grey;'}
                  - if result.is_a? User
                    = @position_name[result.position] + ', ' + result.town.name
                  - elsif result.is_a? Team
                    = 'Drużyna, ' + result.town.name
                  - else
                    = 'Miasto'
                %div{style: 'float: right'}
                  - if current_user.team == nil and result.is_a? Team and result.town == current_user.town
                    = link_to 'Aplikuj', {:controller => 'invitations', :action => 'create', :user_id => current_user.id,
                      :team_id => result.id},:method => :post, :class => 'btn btn-success btn-xs', :style => 'color: white;'
                  - if result.is_a? User and current_user.team != nil and current_user.team.captain == current_user
                    - if current_user.town == result.town and result.team == nil
                      = link_to 'Zaproś do drużyny', {:controller => 'invitations', :action => 'create',
                                              :user_id => result.id, :team_id => current_user.team.id},
                                              :method => :post, :class => 'btn btn-success btn-xs', :style => 'color: white;'
                  - if result.is_a? User
                    = link_to 'Pokaż', user_path(result), :class => 'btn btn-primary btn-xs',  :style => 'color: white;'
                  - elsif result.is_a? Team
                    = link_to 'Pokaż', team_path(result), :class => 'btn btn-primary btn-xs',  :style => 'color: white;'
                  - else
                    = link_to 'Pokaż', town_path(result), :class => 'btn btn-primary btn-xs',  :style => 'color: white;'
                  - if current_user.is_admin
                    - if result.is_a? User
                      = link_to 'Edytuj', edit_user_path(result), :class => 'btn btn-default btn-xs'
                    - elsif result.is_a? Team
                      = link_to 'Edytuj', edit_team_path(result), :class => 'btn btn-default btn-xs'
                    - else
                      = link_to 'Edytuj', edit_town_path(result), :class => 'btn btn-default btn-xs'

    %center
      = will_paginate @results, renderer: BootstrapPagination::Rails