config/routes.rb
Rails.application.routes.draw do
  get 'matches/add_scorers'
  get 'matches/team_matches'
  post 'matches/invitation', to: 'matches#create_invitation'
  delete 'matches/invitation', to: 'matches#destroy_invitation'
  post 'matches/set_dependencies', to: 'matches#set_dependencies'
  resources :matches

  get 'invitations', to: 'invitations#index'

  post 'invitations', to: 'invitations#create'
  delete 'invitations', to: 'invitations#destroy'

  resources :teams do
    member do
      delete 'delete_from_team'
    end
  end

  resources :leagues do
    member do
      get 'scorers'
      get 'matches'
    end
  end

  resources :towns

  devise_for :users, :path_prefix => 'admin'

  resources :users

  get 'home/index'
  get 'home/search'
  get 'home/rules'
  get 'home/about'
  get 'home/contact'

  root 'home#index'

end

app/models/match.rb
class Match < ActiveRecord::Base
  belongs_to :home, class_name: 'Team'
  belongs_to :visitor, class_name: 'Team'
  belongs_to :league

  validates :home_score, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :visitor_score, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :home, presence: true
  validates :visitor, presence: true

  def vs
    "#{home.name} - #{visitor.name}"
  end

  def result
    "#{home_score}:#{visitor_score}"
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_filter :valid_is_admin, only: [:index, :edit, :update]

  respond_to :html

  def index
    @matches = Match.all.paginate(:page => params[:page], :per_page => 20)
    respond_with(@match)
  end

  def show
    @rows = @match.home_score > @match.visitor_score ? @match.home_score : @match.visitor_score
    respond_with(@match)
  end

  def team_matches
    @played = current_user.team.home_matches + current_user.team.visitor_matches
    @played.select!{|played| played.confirmed}
    @played.sort!{|match| match.date}.reverse

    @upcoming = MatchInvitation.where(:sender_id => current_user.team.id, :accepted => true)
    @upcoming += MatchInvitation.where(:receiver_id => current_user.team.id, :accepted => true)
    @upcoming.sort!{|invitation| invitation.date}

    @reports_received = Match.where(:visitor => current_user.team, :confirmed => false)
    @reports_sent = Match.where(:home => current_user.team, :confirmed => false)

    @received_unread = current_user.team.received_match_invitations.select{|inv| inv.read == false and inv.accepted == false}
    @received = current_user.team.received_match_invitations.select{|inv| inv.read and inv.accepted == false}

    @sent = current_user.team.send_match_invitations

    for unread in @received_unread
      unread.read = true
      unread.save
    end
  end

  def add_scorers
    @home = params[:home].to_i
    @score = params[:score].to_i
    if params[:match_id]
      @match = Match.find(params[:match_id])
    end
    @players = User.where(:team_id => params[:team])
    respond_to do |format|
      format.html { render :layout => false }
    end
  end

  def create_invitation
    @invitation = MatchInvitation.new(invitation_params)
    @invitation.save
    redirect_to :back, notice: 'Pomyślnie wysłano propozycję spotkania.'
  end

  def destroy_invitation
    invitation = MatchInvitation.find(params[:id])
    if params[:accept] == '1'
      invitation.accepted = true
      invitation.save
    else
      invitation.destroy
    end
    redirect_to :back
  end

  def new
    @match = Match.new
    if current_user.is_admin
      @homes = @visitors = Team.all
    else
      @homes = Team.where(:id => current_user.team.id)
      @visitors = Team.where(:league_id => current_user.team.league.id)
      @visitors -= [@homes[0]]
    end
    respond_with(@match)
  end

  def edit
    @homes = @visitors = Team.all
  end

  def create
    @match = Match.new(match_params)
    @match.league_id = @match.home.league.id
    set_match_scorers

    if params[:commit] == 'Zapisz'
      @match.confirmed = true
      set_dependencies
    else
      @match.confirmed = false
    end

    @match.save
    respond_with(@match)
  end

  def update
    delete_dependencies
    @match.destroy

    @match = Match.new(match_params)
    @match.league_id = @match.home.league.id
    set_match_scorers
    set_dependencies

    @match.save
    respond_with(@match)
  end

  def destroy
    if params[:dependencies] != 'save'
      delete_dependencies
    end

    @match.destroy
    if params[:dependencies] == 'save'
      redirect_to matches_team_matches_path
    else
      respond_with(@match)
    end
  end

  def set_dependencies
    if params[:id]
      @match = Match.find(params[:id])
      @match.confirmed = true
      @match.save
    end
    @match.home.scored += @match.home_score
    @match.home.lost += @match.visitor_score
    @match.visitor.scored += @match.visitor_score
    @match.visitor.lost += @match.home_score
    if @match.home_score > @match.visitor_score
      @match.home.points += 3
    elsif @match.home_score == @match.visitor_score
      @match.home.points += 1
      @match.visitor.points += 1
    else
      @match.visitor.points += 3
    end
    @match.home.save
    @match.visitor.save

    @match.home_scorers.each do |home_scorer|
      scorer = User.find(home_scorer)
      scorer.goals += 1
      scorer.save
    end
    @match.visitor_scorers.each do |visitor_scorer|
      scorer = User.find(visitor_scorer)
      scorer.goals += 1
      scorer.save
    end

    if params[:id]
      redirect_to matches_team_matches_path
    end
  end

  private
  def set_match
    @match = Match.find(params[:id])
  end

  def match_params
    params.require(:match).permit(:home_id, :visitor_id, :league_id, :visitor_score, :home_score, :date, :confirmed)
    end

  def invitation_params
    params.permit(:sender_id, :receiver_id, :date, :place)
  end

  def valid_is_admin
    if current_user.is_admin == false
      redirect_to root_path, alert: 'Nie posiadasz uprawnień administratora.'
    end
  end

  def delete_dependencies
    @match.home.scored -= @match.home_score
    @match.home.lost -= @match.visitor_score
    @match.visitor.scored -= @match.visitor_score
    @match.visitor.lost -= @match.home_score
    if @match.home_score > @match.visitor_score
      @match.home.points -= 3
    elsif @match.home_score == @match.visitor_score
      @match.home.points -= 1
      @match.visitor.points -= 1
    else
      @match.visitor.points -= 3
    end
    @match.home.save
    @match.visitor.save

    @match.home_scorers.each do |id|
      scorer = User.find(id)
      scorer.goals -= 1
      scorer.save
    end
    @match.visitor_scorers.each do |id|
      scorer = User.find(id)
      scorer.goals -= 1
      scorer.save
    end
  end

  def set_match_scorers
    if params[:home_scorers] != nil
      params[:home_scorers].each do |home_scorer|
        scorer = User.find(home_scorer[1])
        @match.home_scorers += [scorer.id]
      end
    end
    if params[:visitor_scorers] != nil
      params[:visitor_scorers].each do |visitor_scorer|
        scorer = User.find(visitor_scorer[1])
        @match.visitor_scorers += [scorer.id]
      end
    end
  end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_form.html.haml
= form_for @match do |f|
  - if @match.errors.any?
    #error_explanation
      %h2= "#{pluralize(@match.errors.count, "error")} prohibited this match from being saved:"
      %ul
        - @match.errors.full_messages.each do |msg|
          %li= msg
  %center.match{'data-id' => @match.id}
    .form-group
      %h4= 'Data'
      .controls
        = f.text_field :date, class: 'form-control datepicker', style: 'width: 150px;'
  .row
    .col-md-4
    .col-md-4
      .row
        .col-md-5
          %div{style: 'float: right'}
            %table
              %tr
                %td= f.collection_select :home_id, @homes, :id, :name, {}, {class: 'selectpicker home', style: 'float: right;'}
                %td= f.number_field :home_score, min: 0, class: 'form-control home-score',
                                                          style: 'width: 60px; margin-left: 20px;'
            %br
            %div.home-scorers{style: 'float: right;'}
        .col-md-2
          %center
            %h3{style: 'margin-top: 2px;'}= ':'
        .col-md-5
          %table
            %tr
              %td= f.number_field :visitor_score, min: 0, class: 'form-control visitor-score',
                                                          style: 'width: 60px; margin-right: 20px;'
              %td= f.collection_select :visitor_id, @visitors, :id, :name, {}, {class: 'selectpicker visitor'}
          %br
          %div.visitor-scorers
    .col-md-4

  %br
  .actions
    - if current_user.is_admin
      = f.submit 'Zapisz', :class => 'btn btn-primary', :style => 'color: white;', :name => 'commit'
    = f.submit 'Przekaż do weryfikacji', :class => 'btn btn-success', :style => 'color: white;', :name => 'commit'

app/views/matches/add_scorers.html.haml
- if @home == 1
  = fields_for :home_scorers do |scorer|
    - for i in 1..@score
      .space{style: 'height: 10px;'}
      - if @match
        = scorer.collection_select "home_scorer_#{i}", @players, :id, :full_name, {selected: @match.home_scorers[i - 1]},
                                                                                                  {class: 'selectpicker'}
      - else
        = scorer.collection_select "home_scorer_#{i}", @players, :id, :full_name, {}, {class: 'selectpicker'}
- else
  = fields_for :visitor_scorers do |scorer|
    - for i in 1..@score
      .space{style: 'height: 10px;'}
      - if @match
        = scorer.collection_select "visitor_scorer_#{i}", @players, :id, :full_name, {selected: @match.visitor_scorers[i - 1]},
                                                                                                      {class: 'selectpicker'}
      - else
        = scorer.collection_select "visitor_scorer_#{i}", @players, :id, :full_name, {}, {class: 'selectpicker'}

app/views/matches/edit.html.haml
.page-header
  %h1.edit-match= 'Edytuj mecz'

= render 'form'

app/views/matches/index.html.haml
= render 'shared/admin_panel'

%table.table.table-striped
  %thead
    %tr
      %th= 'Data'
      %th= 'Liga'
      %th= 'Mecz'
      %th= 'Wynik'
      %th

  - @matches.each do |match|
    %tr
      %td= match.date
      %td= match.league.description_with_town
      %td= match.vs
      %td= match.result
      %td
        = link_to 'Pokaż', match, :class => 'btn btn-default btn-xs'
        = link_to 'Edytuj', edit_match_path(match), :class => 'btn btn-default btn-xs'
        = link_to 'Usuń', match, :method => :delete, :data => { :confirm => 'Jesteś pewny?' },
                                                    :class => 'btn btn-danger btn-xs', :style => 'color: white;'

%center
  = will_paginate @matches, renderer: BootstrapPagination::Rails
= link_to 'Nowy mecz', new_match_path, :class => 'btn btn-primary', :style => 'color: white;'

app/views/matches/new.html.haml
.page-header
  %h1= 'Nowy mecz'

= render 'form'

app/views/matches/show.html.haml
%center
  %h4
    = 'Data: '
    = @match.date
  %h4
    = @match.league.description_with_town
  %table
    %thead
      %tr
        %th
        %th
        %th{style: 'width: 25px;'}
        %th
        %th
    %tbody
      %tr
        %td
          %h2= link_to @match.home.name, team_path(@match.home)
        %td
          %h2{style: 'text-align: right; margin-left: 25px;'}= @match.home_score
        %td
          %center
            %h2= ':'
        %td
          %h2{style: 'text-align: left; margin-right: 25px;'}= @match.visitor_score
        %td
          %h2= link_to @match.visitor.name, team_path(@match.visitor)
      %tr{style: 'height: 20px'}
      - for i in 0..(@rows - 1)
        %tr{style: 'height: 8px;'}
          %td
            - if i < @match.home_score
              - scorer = User.find(@match.home_scorers[i])
              %h5{style: 'text-align: right; height: 8px;'}= link_to scorer.full_name, user_path(scorer)
          %td{colspan: 3}
          %td
            - if i < @match.visitor_score
              - scorer = User.find(@match.visitor_scorers[i])
              %h5{style: 'height: 8px;'}= link_to scorer.full_name, user_path(scorer)
%br
- if current_user.is_admin
  = link_to 'Edytuj', edit_match_path(@match), :class => 'btn btn-default'
- if @match.confirmed == false and current_user.team == @match.home
  = link_to 'Wycofaj', match_path(@match, :dependencies => 'save'), :method => :delete, :data => { :confirm => 'Jesteś pewny?' },
                                                      :class => 'btn btn-danger', :style => 'color: white;'
- if @match.confirmed == false and current_user.team == @match.visitor
  = link_to 'Akceptuj', matches_set_dependencies_path(:id => @match.id), :method => :post,
                                                      :class => 'btn btn-success', :style => 'color: white;'
  = link_to 'Odrzuć', match_path(@match, :dependencies => 'save'), :method => :delete, :data => { :confirm => 'Jesteś pewny?' },
                                                      :class => 'btn btn-danger', :style => 'color: white;'

app/views/matches/team_matches.html.haml
.row
  .col-md-3
    <br /><br />
    = render 'shared/side_panel'
  .col-md-9
    .page-header
      %h1 Mecze

    %ul.nav.nav-tabs
      %li.active.set-played= link_to 'Rozegrane', '#'
      %li.set-upcoming= link_to 'Nadchodzące', '#'
      - if current_user.team.captain == current_user
        %li.set-reports
          %a{href: '#'}
            ='Oczekujące raporty'
            - if @reports_received.count > 0
              %span.badge= @reports_received.count
        %li.set-received
          %a{href: '#'}
            ='Otrzymane zaproszenia'
            - if @received_unread.count > 0
              %span.badge= @received_unread.count
        %li.set-sent= link_to 'Wysłane zaproszenia', '#'

    %div.played
      %table.table.table-striped
        %thead
          %tr
            %th= 'Data'
            %th= 'Mecz'
            %th= 'Wynik'

        %tbody
          - @played.each do |match|
            %tr
              %td= match.date
              %td= match.vs
              %td= match.result

    %div.upcoming{:style => 'display: none;'}
      %table.table.table-striped
        %thead
          %tr
            %th= 'Data'
            %th= 'Miejsce'
            %th= 'Mecz'

        %tbody
          - @upcoming.each do |invitation|
            %tr
              %td= invitation.date
              %td= invitation.place
              %td= invitation.vs

    - if current_user.team.captain == current_user
      %div.reports{style: 'display: none;'}
        %h4= 'Otrzymane'
        %table.table.table-striped
          %tbody
            - for report in @reports_received
              %tr
                %td
                  %b
                    = 'Drużyna '
                    = link_to report.home.name, team_path(report.home)
                    = ' przekazuje Ci raport meczowy do weryfikacji z '
                    = report.date
                    = '. Wynik: '
                    = report.result
                %td
                  = link_to 'Pokaż', match_path(report),
                                            class: 'btn btn-primary btn-xs', style: 'color: white;'
        %h4= 'Wysłane'
        %table.table.table-striped
          %tbody
            - for report in @reports_sent
              %tr
                %td
                  = 'Przekazałeś drużynie '
                  = link_to report.visitor.name, team_path(report.visitor)
                  = ' raport meczowy do weryfikacji z '
                  = report.date
                  = '. Wynik: '
                  = report.result
                %td
                  = link_to 'Pokaż', match_path(report),
                                            class: 'btn btn-primary btn-xs', style: 'color: white;'

      %div.received{:style => 'display: none;'}
        %table.table.table-striped
          %tbody
            - for unread in @received_unread
              %tr
                %td
                  %b
                    = 'Drużyna '
                    = link_to unread.sender.name, team_path(unread.sender)
                    = ' proponuje spotkanie '
                    = unread.date
                    = ' w: '
                    = unread.place
                %td
                  = link_to 'Akceptuj', matches_invitation_path(:id => unread.id, :accept => 1), method: :delete,
                                            class: 'btn btn-success btn-xs', style: 'color: white;'
                  = link_to 'Odrzuć', matches_invitation_path(:id => unread.id, :accept => 0), method: :delete,
                                          class: 'btn btn-danger btn-xs', style: 'color: white;'
            - for received in @received
              %tr
                %td
                  = 'Drużyna '
                  = link_to received.sender.name, team_path(received.sender)
                  = ' proponuje spotkanie '
                  = received.date
                  = ' w: '
                  = received.place
                %td
                  = link_to 'Akceptuj', matches_invitation_path(:id => received.id, :accept => 1), method: :delete,
                                            class: 'btn btn-success btn-xs', style: 'color: white;'
                  = link_to 'Odrzuć', matches_invitation_path(:id => received.id, :accept => 0), method: :delete,
                                          class: 'btn btn-danger btn-xs', style: 'color: white;'

      %div.sent{:style => 'display: none;'}
        %table.table.table-striped
          %tbody
            - for sent in @sent
              %tr
                %td
                  = 'Zaproponowałeś drużynie '
                  = link_to sent.receiver.name, team_path(sent.receiver)
                  = ' spotkanie '
                  = sent.date
                  = ' w '
                  = sent.place
                %td
                  = link_to 'Wycofaj', matches_invitation_path(:id => sent.id, :accept => 0), method: :delete,
                                          class: 'btn btn-danger btn-xs', style: 'color: white;'

    %br
    - if current_user.team != nil and current_user.team.captain == current_user
      = link_to 'Dodaj raport meczowy', new_match_path, :class => 'btn btn-primary', :style => 'color: white;'